version: '3'
services:
  sleepz-db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sleepz}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-sleepz_development}
    env_file:
      - .env

  sleepz-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=${ENV:-development}
      - DATABASE_URL=postgres://${POSTGRES_USER:-sleepz}:${POSTGRES_PASSWORD}@sleepz-db:5432/${POSTGRES_DB:-sleepz_development}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    env_file:
      - .env
    depends_on:
      - sleepz-db

  sleepz-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 4000:80
